imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:

    dependencies:
        before:
            - command: "mkdir build"
            - mysql -uroot -e '
                CREATE DATABASE IF NOT EXISTS anaxdb;
                USE anaxdb;
                DROP TABLE IF EXISTS Comment2;
                SET NAMES utf8;
                CREATE TABLE Comment2 (`id` INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL, `title` VARCHAR(80), `content` VARCHAR(455) NOT NULL, `userMail` VARCHAR(80) NOT NULL, `userId` INTEGER) ENGINE INNODB CHARACTER SET utf8 COLLATE utf8_swedish_ci;
                INSERT INTO `Comment2` (`title`, `content`, `userMail`, `userId`) VALUES
                	("ForTest", "test", "admin@hotmail.com", "1");'


        after:
            - "composer require --dev phpunit/phpunit"

    tests:
        override:
            -
                command: "vendor/bin/phpunit --configuration .phpunit.xml"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"
