imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:

    dependencies:
        before:
            -
                command: "mkdir build"
        after:
            - "composer require --dev phpunit/phpunit"

    tests:
        project_setup:
            before:
                - mysql -e '
                    USE anaxdb;
                    DROP TABLE IF EXISTS Comment2;
                    SET NAMES utf8;
                    CREATE TABLE Comment2 (`id` INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL, `title` VARCHAR(80), `content` VARCHAR(455) NOT NULL, `userMail` VARCHAR(80) NOT NULL, `userId` INTEGER) ENGINE INNODB CHARACTER SET utf8 COLLATE utf8_swedish_ci;'
        override:
            -
                command: "vendor/bin/phpunit --configuration .phpunit.xml"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"
